info:
  app:
    name: activity-be

server:
  port: 30026

logging:
  level:
    com:
      cema: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
app:
  region: AR

spring:
  profiles:
    active: local
  application:
    name: activity-be
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.100.5:5432/activity
    username: activity
    password: Z+8_6mKrw%Gq3_Sp
back-end:
  users:
    url: "http://localhost:30023/v1/users"
  bovine:
    url: "http://localhost:30024/v1/"
  administration:
    url: "http://localhost:30025/v1/"

---
spring:
  datasource:
    url: jdbc:postgresql://192.168.100.5:5432/activity
  config:
    activate:
      on-profile: qa
back-end:
  users:
    url: "http://192.168.100.5:30023/v1/users"
  bovine:
    url: "http://192.168.100.5:30024/v1/"
  administration:
    url: "http://192.168.100.5:30025/v1/"

---
spring:
  datasource:
    url: jdbc:postgresql://192.168.100.6:5432/activity
  config:
    activate:
      on-profile: prod
back-end:
  users:
    url: "http://192.168.100.6:30023/v1/users"
  bovine:
    url: "http://192.168.100.6:30024/v1/"
  administration:
    url: "http://192.168.100.6:30025/v1/"
